name: 'trigger gitlab'
on: [push]
jobs:
  pipeline:
    name: run pipeline
    runs-on: ubuntu-latest
    steps:
    - name: push changes
      run: |
        git init
        git remote set-url origin git@gitlab.com:gl-demo-ultimate-smorris/playgrounds/github-trigger.git
        git push origin ${{ github.sha }}:${GITHUB_REF##*/}
    - name: trigger job
      run: |
        curl --request POST \
        --form token=${{ secrets.TOKEN }} \
        --form ref=${GITHUB_REF##*/} \
          "https://gitlab.com/api/v4/projects/55093078/trigger/pipeline"
